PsiTransfer
sloppyio/quickstarters pull request #41
Opened 2020-12-21 15:16 UTC by teulaert

Add PsiTransfer to the Quickstarters. A simple open source self-hosted file sharing solution. It's an alternative to paid services like Dropbox, WeTransfer.

2020-12-22 08:21 UTC, FrontEndCoffee requested changes
It seems that something has gone wrong with your branching, the `psitransfer` branch also contains the changes for you earlier `rocketchat` branch. Please remove these changes from this branch.

2020-12-22 08:21 UTC, FrontEndCoffee commented on rocketchat/README.md
> +
These Rocketchat related changes should not be in this PsiTransfer PR

2020-12-22 08:21 UTC, FrontEndCoffee commented on rocketchat/rocketchat.json
>            "volumes": [
These Rocketchat related changes should not be in this PsiTransfer PR

2020-12-22 08:21 UTC, FrontEndCoffee commented on rocketchat/rocketchat.yml
> -  frontend:
These Rocketchat related changes should not be in this PsiTransfer PR

2021-01-04 23:48 UTC, timmakken approved these changes

2021-01-04 23:49 UTC, merged